<?php

namespace AppBundle\Repository;

/**
 * ImageSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSliderRepository extends \Doctrine\ORM\EntityRepository
{
    public function recentImages(){
        return $this->getEntityManager()
            ->createQuery('SELECT a.id, a.image, a.dateAdded FROM AppBundle:ImageSlider a ORDER BY a.dateAdded DESC')
            ->getResult();
    }
}
