<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExistingUsernames(){
        return $this->getEntityManager()
            ->createQuery('SELECT a.username FROM AppBundle:User a')
            ->getResult();
    }
}
